"""added offers and appliences

Revision ID: d0af5053d328
Revises: b5435d54e545
Create Date: 2024-03-26 16:14:37.677329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0af5053d328'
down_revision: Union[str, None] = 'b5435d54e545'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appliance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('img1', sa.String(length=128), nullable=False),
    sa.Column('img2', sa.String(length=128), nullable=True),
    sa.Column('img3', sa.String(length=128), nullable=True),
    sa.Column('address', sa.String(length=512), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('lon', sa.REAL(), nullable=True),
    sa.Column('lat', sa.REAL(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.String(length=2048), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('rooms', sa.String(length=8), nullable=False),
    sa.Column('price', sa.REAL(), nullable=False),
    sa.Column('area', sa.REAL(), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('renovation', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appliances_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appliance_id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['appliance_id'], ['appliance.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['offer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appliances_map')
    op.drop_table('offer')
    op.drop_table('appliance')
    # ### end Alembic commands ###
